import hashlib
import re
from typing import Any, Dict, List, Tuple


class AutonomyEngine:
    """Stateful supervisor for autonomous planning.

    Progress is evidence-driven: broad categories (for example "identity") are
    useful context, but they are not evidence by themselves. A new progress
    event requires at least one previously unseen, normalized fact extracted
    from the command output, or a genuinely new session capability.
    """

    _VOLATILE_LINE = re.compile(
        r"(?:^|\s)(?:time|elapsed|duration|seconds?|timestamp)\s*[:=]\s*[^\s]+",
        re.I,
    )

    def __init__(self, target: str):
        self.target = target

    @staticmethod
    def _normalize(text: str) -> str:
        return re.sub(r"\s+", " ", str(text or "").strip())

    @classmethod
    def _fact_lines(cls, output: str) -> List[str]:
        """Extract stable, non-diagnostic facts from tool output.

        This intentionally avoids treating generic words such as 'user' or
        'service' as progress. Each stable output line becomes a compact
        evidence fingerprint so repeated LDAP/SMB/RPC queries do not consume
        the progress budget merely because they belong to a known category.
        """
        facts: List[str] = []
        seen = set()
        for raw in str(output or "").splitlines():
            line = cls._normalize(raw)
            if not line:
                continue
            line = cls._VOLATILE_LINE.sub(" ", line)
            lower = line.lower()
            if lower.startswith(("warning:", "error:", "debug:", "traceback")):
                continue
            if lower in {"success", "done", "completed", "ok"}:
                continue
            # Ignore pure progress/noise lines generated by common CLI tools.
            if re.fullmatch(r"[-=_. ]+", line):
                continue
            if len(line) < 3:
                continue
            fingerprint = hashlib.sha256(line.lower().encode("utf-8", errors="ignore")).hexdigest()[:20]
            if fingerprint not in seen:
                seen.add(fingerprint)
                facts.append(fingerprint)
        return facts[:128]

    @staticmethod
    def _evidence_types(output: str) -> List[str]:
        text = str(output or "").lower()
        found = []
        patterns = {
            "network": ("open", "tcp", "udp", "service"),
            "identity": ("user", "account", "principal", "domain"),
            "group": ("group", "member", "memberof"),
            "share": ("share", "smb", "cifs"),
            "credential": ("password", "credential", "hash", "ntlm", "secret"),
            "session": ("authenticated", "authentication", "session", "shell"),
            "privilege": ("administrator", "system", "root", "privilege"),
            "file": ("file", "directory", "loot", "downloaded"),
        }
        for name, terms in patterns.items():
            if any(t in text for t in terms):
                found.append(name)
        return found

    @staticmethod
    def _session_signal(command: str, output: str, returncode: Any) -> bool:
        if returncode not in (0, None):
            return False
        text = (str(command or "") + " " + str(output or "")).lower()
        return any(
            x in text
            for x in (
                "authenticated",
                "psexec",
                "wmiexec",
                "smbexec",
                "evil-winrm",
                "interactive shell",
            )
        )

    @classmethod
    def _meaningful_progress(
        cls,
        returncode: Any,
        new_evidence_facts: List[str],
        new_session: bool,
    ) -> bool:
        if returncode not in (0, None):
            return False
        return bool(new_evidence_facts or new_session)

    def observe(self, state: Dict[str, Any], entry: Dict[str, Any]) -> Dict[str, Any]:
        old = dict(state.get("autonomy") or {})
        output = str(entry.get("output", ""))
        command = str(entry.get("command", ""))

        digest = (
            hashlib.sha256(self._normalize(output).encode()).hexdigest()[:16]
            if output
            else ""
        )

        evidence = list(old.get("evidence_types", []))
        current_evidence = self._evidence_types(output)
        new_evidence_types = [item for item in current_evidence if item not in evidence]
        for item in new_evidence_types:
            evidence.append(item)

        known_facts = set(old.get("evidence_fingerprints", []))
        current_facts = self._fact_lines(output)
        new_evidence_facts = [item for item in current_facts if item not in known_facts]
        known_facts.update(new_evidence_facts)

        sessions = list(old.get("sessions", []))
        session_signal = self._session_signal(command, output, entry.get("returncode"))
        new_session = False
        if session_signal:
            sid = hashlib.sha256(self._normalize(command).encode()).hexdigest()[:12]
            if sid not in {s.get("id") for s in sessions if isinstance(s, dict)}:
                sessions.append(
                    {"id": sid, "source": command[:240], "step": entry.get("step")}
                )
                new_session = True

        history_digests = list(old.get("output_digests", []))
        if digest and digest not in history_digests:
            history_digests.append(digest)

        progress = self._meaningful_progress(
            entry.get("returncode"),
            new_evidence_facts,
            new_session,
        )
        streak = int(old.get("no_progress_streak", 0))
        streak = 0 if progress else streak + 1

        return {
            "evidence_types": evidence[-32:],
            "evidence_fingerprints": list(known_facts)[-512:],
            "sessions": sessions[-16:],
            "output_digests": history_digests[-64:],
            "progress_events": int(old.get("progress_events", 0)) + (1 if progress else 0),
            "no_progress_streak": streak,
            "last_progress_step": (
                entry.get("step") if progress else old.get("last_progress_step")
            ),
            "last_action": command[:240],
            "last_new_evidence": new_evidence_types,
            "last_new_evidence_facts": new_evidence_facts[:32],
            "last_progress": progress,
        }

    def context(self, state: Dict[str, Any]) -> Dict[str, Any]:
        a = state.get("autonomy") or {}
        return {
            "evidence_types": a.get("evidence_types", []),
            "evidence_fingerprints_count": len(a.get("evidence_fingerprints", [])),
            "sessions": a.get("sessions", []),
            "progress_events": a.get("progress_events", 0),
            "last_progress_step": a.get("last_progress_step"),
            "no_progress_streak": a.get("no_progress_streak", 0),
            "last_new_evidence": a.get("last_new_evidence", []),
            "last_new_evidence_facts": a.get("last_new_evidence_facts", []),
            "last_progress": a.get("last_progress", False),
            "last_action": a.get("last_action", ""),
        }
